### ISSUE TITLE
Peptide Uniqueness checker can't handle long sequence

### ISSUE THREAD

**Issue by fabianegli** [calipho-sib/nextprot-ui#21]
It seems that the peptide uniqueness checker has a weird behaviour when long sequences are submitted. The funny rotating and direction changing color spiral spins and spins and spins and ...

Tried with 1000 times "PEPTIDE": `python -c 'print("PEPTIDE"*1000)'`

**Comment by kwsamarasinghe** [comment]
Hi Fabian, Thanks for the report. We will check it and update you on this.

**Comment by kwsamarasinghe** [comment]
Hi Fabian, 
Currently version has a limit on a given peptide to be submitted. In our coming release, we will improve the interface to give more informative instructions and error/warning messages.
Thank you for pointing out the issue.

**Comment by kwsamarasinghe** [comment]
Hi, We have updated the peptide uniqueness checker with better error handling and error messages. Thanks for the issue.
